codebook/urls.py
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import re_path
from django.views.generic import RedirectView
from codebook import settings
from topics.views import users
from django.contrib.auth import views as auth_views

password_reset_confirm = \
    "^_reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$"

urlpatterns = [
                  re_path(r'^_admin/', admin.site.urls),
                  re_path(r'^_password_reset/$', users.password_reset_view, name='password_reset'),
                  re_path(password_reset_confirm, auth_views.PasswordResetConfirmView, name='password_reset_confirm'),
                  re_path(r'^_password_reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_done'),
                  re_path(r'^favicon.ico$',
                      RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'), permanent=False)),
                  re_path(r'', include('topics.urls', namespace='topics')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

topics/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views

from topics.views import sso
from .views import users
from .views import topics

app_name = 'topics'

urlpatterns = [
    # User authentication
    re_path(r'^_login/$', users.login_view, name='login'),
    re_path(r'^_login/sso$', sso.sso),
    re_path(r'^_accounts/login/$', users.login_view, name='login'),
    re_path(r'^_create_account/$', users.create_account_view, name='create_account'),
    re_path(r'^_logout/$', users.logout_view, name='logout'),
    re_path(r'^_reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_complete'),
    # Topics
    re_path(r'^_tag/$', topics.tag_topic, name='tag_topic'),
    re_path(r'^_icon/([0-9]+)\.ico$', topics.get_link_icon, name='get_link_icon'),
    re_path(r'^(.*)/$', topics.get_topic, name='get_topic'),
    re_path(r'^()$', topics.get_topic, name='get_topic'),
]

topics/views/sso.py
import base64
import hmac
import hashlib
import urllib.parse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.conf import settings


@login_required
def sso(request):
    payload = request.GET.get('sso')
    signature = request.GET.get('sig')

    if None in [payload, signature]:
        return HttpResponseBadRequest('No SSO payload or signature. Please contact support if this problem persists.')

    # Validate the payload

    payload = bytes(urllib.parse.unquote(payload), "utf-8")
    decoded = base64.decodebytes(payload)

    key = bytes(str(settings.DISCOURSE_SSO_SECRET), "utf-8")
    h = hmac.new(key, payload, digestmod=hashlib.sha256)
    this_signature = h.hexdigest()

    if this_signature != signature:
        return HttpResponseBadRequest('Invalid payload. Please contact support if this problem persists.')

    # Build the return payload

    qs = urllib.parse.parse_qs(decoded)
    params = {
        'nonce': qs[b'nonce'][0],
        'email': request.user.email,
        'external_id': request.user.id,
        'username': request.user.username,
    }

    return_payload = base64.encodebytes(bytes(urllib.parse.urlencode(params), "utf-8"))
    h = hmac.new(key, return_payload, digestmod=hashlib.sha256)
    query_string = urllib.parse.urlencode({'sso': return_payload, 'sig': h.hexdigest()})

    # Redirect back to Discourse

    url = qs[b'return_sso_url'][0].decode('utf-8')
    return HttpResponseRedirect('%s?%s' % (url, query_string))

topics/views/topics.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.db import IntegrityError
from django.http import HttpResponse, Http404
from django.shortcuts import redirect, render
from django.template import loader, RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from topics.helpers import view_helpers
from topics.helpers.rubric import rubric
from topics.models import Link, Tag

view_helpers.setup()


def paginate_links(links, page):
    paginator = Paginator(links, 25)

    try:
        return paginator.page(page)
    except PageNotAnInteger:
        return paginator.page(1)
    except EmptyPage:
        return paginator.page(paginator.num_pages)


def tag_topic(request):
    if request.POST:
        if request.POST.get("link_tag"):
            save_tag(request, "")
            return redirect("topics:tag_topic")
    template = loader.get_template('topics/tag_link.html')
    context = RequestContext(request, {
        'link': Link.get_no_tag_link(current_site=get_current_site(request)),
        'rubric': rubric
    })
    return HttpResponse(template.render(context))


def get_topic(request, topic_name):
    selected_tags = topic_name.strip("/")
    if selected_tags:
        selected_tags = selected_tags.split("/")
    else:
        selected_tags = []

    if request.POST:
        if request.POST.get("link_tag"):
            return save_tag(request, topic_name)
        if request.POST.get("delete_tag"):
            return delete_tag(request, selected_tags)
        else:
            return save_link(request, topic_name)

    template = 'topics/show_topic.html'
    links = Link.get_all_links(get_current_site(request), selected_tags)
    links = paginate_links(links, request.GET.get('page'))

    top_tags = list(Tag.get_top_tag_list(get_current_site(request), selected_tags))
    if len(links) < 6:
        top_tags = top_tags[:-1]
    context = {
        'links': links,
        'top_tags_first': top_tags[:1],
        'top_tags_rest': top_tags[1:],
        'selected_tags': selected_tags
    }
    return render(request, template, context)


def get_link_icon(request, link_id):
    l = Link.objects.filter(id=int(link_id)).values('icon_data', 'icon_content_type').first()
    if not l:
        raise Http404()
    response = HttpResponse(content_type=l['icon_content_type'])
    response.write(l['icon_data'])
    return response


@login_required
def save_tag(request, topic_name):
    tag_list_raw = request.POST.get("tag_text")
    link_title = request.POST.get("link_title")
    link_delete = request.POST.get("link_delete") == "delete"
    link_id = int(request.POST.get("link_tag"))
    link_type = request.POST.get("type")
    link_difficulty = request.POST.get("difficulty")
    link_quality = request.POST.get("quality")

    tag_list = tag_list_raw.lstrip("#").replace("#", ",").split(",")
    Link.save_ratings(link_id, link_type, link_difficulty, link_quality)
    if link_delete:
        Link.delete_link(link_id)
    else:
        if link_title:
            Link.rename_link(link_id, link_title)
        Tag.save_tags(link_id, tag_list, request.user)
    return redirect("topics:get_topic", topic_name)


@login_required
def delete_tag(_, selected_tags):
    Tag.delete_tag(selected_tags[-1])
    return redirect("topics:get_topic", selected_tags[:-1])


@login_required
def save_link(request, topic_name):
    try:
        Link.save_link(request.POST.get('url'), request.user, get_current_site(request))
    except IntegrityError:
        messages.error(request, 'Link already posted.')
    return redirect("topics:get_topic", topic_name)

topics/views/users.py
from django.contrib.auth import logout
from django.contrib.auth import views
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import redirect

from topics.settings_context import settings_context


def create_account_view(_):
    return HttpResponseForbidden()


def login_view(request):
    extra_context = {
        'next': request.GET.get("next"),
        'fromlink': True if request.GET.get("fromlink") == 'true' else False
    }
    extra_context.update(settings_context(request))
    template_response = views.login(request, extra_context=extra_context)
    return template_response


def password_reset_view(request):
    extra_context = {
    }
    template_response = views.password_reset(request, extra_context=extra_context)
    return template_response


def password_reset_confirm_view(request):
    extra_context = {
    }
    template_response = views.password_reset(request, extra_context=extra_context)
    return template_response


def logout_view(request):
    if request.POST:
        next_link = "." if not request.POST.get("next") else request.POST.get("next")
        logout(request)
        return redirect(next_link)

    raise Http404("Logout must be called from the link on the website, not directly")

topics/templates/includes/footer.html
<footer class="site-footer">
    <nav class="wrapper">
        <nav class="wrapper">
            <ul>
                <li><a href="https://creativecommons.org/licenses/by/4.0/">(CC BY 4.0)</a></li>
            </ul>
        </nav>
    </nav>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
{% load pipeline %}
{% javascript 'script' %}

topics/templates/includes/head.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">


<meta name="description" content="{{ site.description }}">
<link rel="icon" href="/_static/favicon.ico">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77260946-1', 'auto');
  ga('send', 'pageview');

</script>

{% load pipeline %}
{% stylesheet 'style' %}

topics/templates/includes/header.html
{% load static %}
<header class="site-header">
    <div class="wrapper">
        <div class="site-title">
            {% if site_logo == "logos/snc.svg" %}
                <img src="{% static site_logo %}" style="width: 60px" class="site-icon"/>
            {% else %}
                <img src="{% static site_logo %}" class="site-icon"/>
            {% endif %}
            <a href="/" class="site-title-text quick-link">{{ site.header }}</a>
        </div>
        <div class="site-login">
            {% if user.is_authenticated %}
                <form action="/_logout/" method="POST">
                    {% csrf_token %}
                    {% if user.is_staff %}
                        <a href="{% url 'admin:index' %}">Admin</a>
                    {% endif %}
                    <input type="hidden" value="{{ request.path }}" name="next">
                    <input type="submit" value="Log out">
                </form>
            {% endif %}
        </div>
        <nav class="site-nav {% if editing_topic %}editing-topic{% endif %}">
            {% include 'includes/navbar.html' with top_tags=top_tags_first %}
        </nav>
    </div>
</header>

topics/templates/includes/link.html
<div class="link_block">
    {% if link.icon %}
        <img class="icon" src="{% url 'topics:get_link_icon' link.id %}"/>
    {% endif %}
    <a class="link_url" href="{{ link.link }}">
        {{ link.title }}
    </a>
    {% if user.is_authenticated %}
        <form action="" method="post" class="link-tag">
            {% csrf_token %}
            <input type="hidden" name="link_tag" value="{{ link.id }}"/>
            <input type="text" name="tag_text" class="tag_text" title="Tag" placeholder="#tag"/>
            <input type="text" name="link_title" class="link_title" title="Link Title" placeholder="Link Title"/>
            <label class="link-delete"><input type="checkbox" name="link_delete" value="delete"><span>Delete</span>
            </label>
            {% if rubric %}
                {% for list_type, list in rubric %}
                    <h2 class="list-type-title">{{ list_type|title }}</h2>
                    <ul>
                        {% for value, item in list %}
                            <li><label><input type="radio" name="{{ list_type }}" value="{{ value }}"><span>{{ item }}</span></label></li>
                        {% endfor %}
                    </ul>
                {% endfor %}
            {% endif %}
            <input type="submit"/>
        </form>
    {% endif %}
    <div class="tags">
        {% for tag in link.tags.all|slice:":7" %}
            <a href="{% url 'topics:get_topic' tag.slug %}"
               class="quick-link {% if tag.slug in selected_tags %}active{% endif %}">{{ tag.text.split|join:"&nbsp;" }}</a>
        {% endfor %}
    </div>
</div>

topics/templates/includes/navbar.html
{% for tag_list in top_tags %}
    <div class="site-header-nav">
        <div class="wrapper">
            <div class="site-nav {% if editing_topic %}editing-topic{% endif %}">
                <ul>
                    {% for tag in tag_list %}
                        <li class="{% if tag.active %}active{% endif %}">
                                <a class="page-link quick-link"
                                   href="{% url 'topics:get_topic' tag.path|join:"/" %}">{{ tag.text }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endfor %}